# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: News
    url: newsfeed
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Events
    url: event
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Contact
    url: contact
    weight: 60
  - name: Project
    url: project
    weight: 70
  - name: Teaching
    url: teaching
    weight: 80
