# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

#theme: minimal
#day_night: false
#font: native
#font_size: L

appearance:
  theme_day: minimal
  theme_night: dark
  font: minimal
  font_size: L


# SEO

site_type: Organization
local_business_type: ''
org_name: ''
description: My research group description.
twitter: 'https://twitter.com/mwmkaouer'

# Contact (edit or remove options as required)

email: mwmvse@rit.edu
phone: (313) 338 48 two 9
address:
  street: 92 Lomb Memorial Drive
  city: Rochester
  region: NY
  postcode: '14623-5608'
  country: United States
  country_code: US
coordinates:
  latitude: '43.091969'
  longitude: '-77.674690'
directions: Enter Golisano Building and find Office 70-1519 on ground Floor
office_hours:
  - 'Tuesday 03:00 PM to 04:00 PM'
  - 'Thursday 03:00 PM to 04:00 PM'
appointment_url: 'mailto:mwmvse@rit.edu'
contact_links:
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
math: false
diagram: false
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'UA-69945343-1'
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
  analytics:
    microsoft_clarity: 'cv08wwaqws'

cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
